### ISSUE TITLE
adapter does not work with dotnetcore sdk project files

### ISSUE THREAD

**Issue by jackfoxy** [adamchester/expecto-adapter#38]
````
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net47</TargetFramework>
````
test with [my test branch](https://github.com/jackfoxy/personalServer/tree/newprojectsystem
)

````
[1/22/2018 3:36:26 PM Informational] Running all tests (9999.0.0.0)
[1/22/2018 3:36:26 PM Informational] Creating test host for E:\GitRepos\PersonalServer\tests\PersonalServer.Tests\bin\Debug\net47\PersonalServer.Tests.exe
[1/22/2018 3:36:26 PM Informational] Executing tests in assembly E:\GitRepos\PersonalServer\tests\PersonalServer.Tests\bin\Debug\net47\PersonalServer.Tests.exe
[1/22/2018 3:36:26 PM Error] System.MissingMethodException: Method not found: 'Void ExpectoConfig..ctor(Boolean, Int32, Microsoft.FSharp.Core.FSharpOption`1<System.TimeSpan>, System.TimeSpan, Double, Boolean, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.Test,Expecto.Test>, TestPrinters, Expecto.Logging.LogLevel, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.TestCode,Expecto.SourceLocation>, Int32, Int32, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Boolean)'.
   at Execution.ExecuteProxy.ExecuteTests()
   at Execution.ExecuteProxy.ExecuteTests()
   at <StartupCode$Expecto-VisualStudio-TestAdapter>.$Execution.clo@180-10.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Execution.ExpectoTestExecutor.runAllExecutors()
   at Execution.ExpectoTestExecutor.Microsoft-VisualStudio-TestPlatform-ObjectModel-Adapter-ITestExecutor-RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
[1/22/2018 3:36:26 PM Warning] No test is available in E:\GitRepos\PersonalServer\tests\PersonalServer.Tests\bin\Debug\net47\PersonalServer.Tests.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

````

**Comment by MNie** [comment]
Related to [#211](https://github.com/haf/expecto/issues/211)

**Comment by MNie** [comment]
@jackfoxy could you check if Expecto.VisualStudio.TestAdapter references Expecto in version > 5.1.1?
If my project references only a `Expecto.VisualStudio.TestAdapter` it references an Expecto in version 5.0:
![image](https://user-images.githubusercontent.com/7689103/35293540-52a01bde-0074-11e8-8345-6f182f763e6a.png)
But if I install explicitly the newest Expecto everything seems to work fine.
![image](https://user-images.githubusercontent.com/7689103/35293577-71f9243a-0074-11e8-9e56-0946e58050f9.png)

**Comment by MNie** [comment]
@jackfoxy I released a [6.0.1](https://www.nuget.org/packages/Expecto.VisualStudio.TestAdapter/6.0.1) with restriction for Expecto. Please check if it works for you :)

**Comment by jackfoxy** [comment]
Thanks for the quick response. Just picked up 6.0.1 and 155 of 156 tests passed, as expected. @MNie

**Comment by MNie** [comment]
@jackfoxy great to hear :)
