### ISSUE TITLE
Method not found in ExpectoConfig..ctor

### ISSUE THREAD

**Issue by jackfoxy** [adamchester/expecto-adapter#44]
It seems like this one has popped up and been fixed before.

```
Executing tests in assembly E:\GitRepos\DependentTypes\tests\DomainLib.Tests\bin\Debug\net472\DomainLib.Tests.exe
[9/30/2018 12:28:16 PM Error] System.MissingMethodException: Method not found: 'Void ExpectoConfig..ctor(Boolean, Int32, Microsoft.FSharp.Core.FSharpOption`1<System.TimeSpan>, System.TimeSpan, Double, Boolean, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.Test,Expecto.Test>, TestPrinters, Expecto.Logging.LogLevel, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.TestCode,Expecto.SourceLocation>, Int32, Int32, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Boolean, Boolean)'.
   at Execution.ExecuteProxy.ExecuteTests()
   at Execution.ExecuteProxy.ExecuteTests()
   at <StartupCode$Expecto-VisualStudio-TestAdapter>.$Execution.clo@180-10.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Execution.ExpectoTestExecutor.runAllExecutors()
   at Execution.ExpectoTestExecutor.Microsoft-VisualStudio-TestPlatform-ObjectModel-Adapter-ITestExecutor-RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
```
building with dotnet\sdk\2.1.500-preview-009297
test exe is net472
Expecto adapter version 9
VS 15.9.0 Preview 2.0 or VS 15.8.5

Reproduction steps:
clone this commit of DependentTypes
https://github.com/jackfoxy/DependentTypes/commit/6474cf9ef818861978484540f595c492dff0e564

Do test discovery and run all tests.

**Comment by MNie** [comment]
@jackfoxy I think it is related to a breaking change in expecto. New package pushed to a nugget. Please give a sign if it helps you.

**Comment by jackfoxy** [comment]
@MNie fixed. Thanks.
