### ISSUE TITLE
Adapter broke with Expecto 8.10

### ISSUE THREAD

**Issue by matthid** [adamchester/expecto-adapter#48]
After Upgrading to latest Expecto I was greeted with the following error

```
2019-04-18 12:20:32 Error] System.MissingMethodException: Method not found: 'Void ExpectoConfig..ctor(Boolean, Int32, Microsoft.FSharp.Core.FSharpOption`1<System.TimeSpan>, System.TimeSpan, Double, Boolean, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.Test,Expecto.Test>, TestPrinters, Expecto.Logging.LogLevel, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpFunc`2<Expecto.TestCode,Expecto.SourceLocation>, Int32, Int32, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Boolean, Boolean, Boolean)'.
   at Execution.ExecuteProxy.ExecuteTests()
   at Execution.ExecuteProxy.ExecuteTests()
   at <StartupCode$Expecto-VisualStudio-TestAdapter>.$Execution.clo@182-10.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Execution.ExpectoTestExecutor.runAllExecutors()
   at Execution.ExpectoTestExecutor.Microsoft-VisualStudio-TestPlatform-ObjectModel-Adapter-ITestExecutor-RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
```

https://www.nuget.org/packages/Expecto/8.10.0

Downgrading to `< 8.10` (= 8.9.1) helped

using VS2017

**Comment by olivercoad** [comment]
Looks like this issue
https://github.com/haf/expecto/issues/318,
https://github.com/YoloDev/YoloDev.Expecto.TestSdk/issues/15

**Comment by jackfoxy** [comment]
I'm seeing the same problem. Downgrading Expecto to 8.9.1 did fix it.
